# e-commerce-tenant-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: e-commerce
  name: e-commerce-tenant
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  - secrets
  - services
  - pods
  - replicationcontrollers
  - pods/exec
  - events
  - serviceaccounts
  verbs:
  - "*"
- apiGroups:
  - "apps"
  resources:
  - deployments
  - replicasets
  - statefulsets
  - daemonsets
  verbs:
  - "*"
- apiGroups:
  - "extensions"
  resources:
  - ingresses
  verbs:
  - "*"
- apiGroups:
  - "batch"
  resources:
  - jobs
  - cronjobs
  verbs:
  - "*"
- apiGroups:
  - "policy"
  resources:
  - poddisruptionbudgets
  verbs:
  - "*"
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - persistentvolumeclaims/status
  verbs:
  - "*"
- apiGroups:
  - "storage.k8s.io"
  resources:
  - storageclasses
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "autoscaling"
  resources:
  - horizontalpodautoscalers
  verbs:
  - "*"