apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tenant-1
  namespace: e-commerce
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: storage-class-tenant-1