apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-tenant-1
spec:
  volumeMode: Filesystem
  capacity:
    storage: 500Mi
  accessModes:
    - ReadWriteMany
  storageClassName: storage-class-tenant-1
  hostPath:
    path: "/tenant-1/data"
