apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tenant-1-test-wrong-storage-class
  namespace: e-commerce
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: storage-class-tenant-2