apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-tenant-2
  namespace: streaming
spec:
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  resources:
    requests:
      storage: 10Mi
  storageClassName: storage-class-tenant-2