# group-rolebinding-tenant-1.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: tenant-2-rolebinding
  namespace: streaming
subjects:
- kind: Group
  name: tenant-2
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: streaming-tenant
  apiGroup: rbac.authorization.k8s.io
